### ISSUE TITLE
[Helm] Don't use LoadBalancer service type by default (work behind a proxy)

### ISSUE THREAD

**Issue by KIVagant** [benc-uk/kubeview#71]
```yaml
#service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeview.fullname" . }}
  labels:
{{ include "kubeview.labels" . | indent 4 }}
spec:
  {{ if .Values.ingress.enabled }}
  type: ClusterIP
  {{ else }}
  type: LoadBalancer
  {{ end }}
...
```

We use a proxy that covers authorization logic and in such setup the app does not need neither Ingress, nor LoadBalancer. 

Please add support for `ClusterIP` no matter if Ingress is enabled or not.
