### ISSUE TITLE
[Helm] Support service annotations

### ISSUE THREAD

**Issue by KIVagant** [benc-uk/kubeview#72]
Please add support for custom object annotations.

```yaml
# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeview.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
...
```

```yaml
# values.yaml

service:
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
  type: ClusterIP     # ← as per https://github.com/benc-uk/kubeview/issues/71

```

Same improvement can be added to other Yaml-resources.

Additionally, it would be nice to support extra labels.
